const ds236Articles = {
  "artículo 1": "Aprueba las Bases Generales Reglamentarias para los contratos de ejecución de obras que celebren los Servicios de Vivienda y Urbanización (SERVIU).",
  "artículo 2": "Define términos clave como Aclaraciones, Adiciones, Administración Delegada, Bases Administrativas Generales y Especiales, Bases Técnicas, Capacidad Económica, Comisión Técnica, Contratista, Gastos Generales, Inspección Técnica de la Obra, Itemizado de Partidas, Licitación, entre otros.",
  "artículo 5": "Establece los sistemas de contratación: 1) Precio a Suma Alzada (modalidades: proyecto por SERVIU o oferente, precio por SERVIU o oferente, Concursos Ofertas); 2) Serie de Precios Unitarios; 3) Administración Delegada. Define el presupuesto compensado según cada sistema.",
  "artículo 10": "El decreto regula los contratos del SERVIU. El MINVU supervisa el cumplimiento y resuelve consultas técnicas o administrativas de los SERVIU.",
  "artículo 11": "Autoriza al SERVIU a usar derechos y patentes de proyectos de Concursos Ofertas para terminar obras en caso de liquidación anticipada.",
  "artículo 12": "En licitaciones por serie de precios unitarios, el valor se fija por precios unitarios del proponente multiplicados por cantidades de obra del SERVIU, que son informativas.",
  "artículo 13": "La contratación por administración delegada se realiza por propuesta privada o trato directo, con causales justificadas.",
  "artículo 14": "En administración delegada, se reembolsan gastos directos comprobados, con posibles premios o multas según costos y bases especiales.",
  "artículo 16": "En administración delegada, el contratista cubre gastos de oficina central, viajes, estudios y sobresueldos con el porcentaje de gastos de administración.",
  "artículo 17": "Los reembolsos en administración delegada se hacen mediante rendiciones de cuentas, con facturas a nombre del SERVIU.",
  "artículo 20": "Los gastos de administración y honorarios en administración delegada se pagan en cuotas cada 14 días, proporcional al avance físico, reajustados por U.F.",
  "artículo 21": "La adquisición de materiales y arrendamiento de maquinaria en administración delegada requiere autorización de la I.T.O., según artículos 140 y siguientes.",
  "artículo 22": "Las propuestas son solicitadas por el Director del SERVIU, participando contratistas inscritos en el RENAC según el presupuesto oficial estimativo.",
  "artículo 23": "Obras que requieran registro especial del RENAC deben tenerlo vigente antes del llamado a licitación.",
  "artículo 26": "El plazo para abrir propuestas no será inferior a 15 días desde la publicación del llamado o disponibilidad de antecedentes.",
  "artículo 27": "Solo contratistas inscritos en el RENAC pueden presentar propuestas o ejecutar obras por trato directo, acreditado con certificado vigente.",
  "artículo 28": "Los proponentes deben presentar, 7 días antes de la apertura, nómina de contratos en ejecución, certificado RENAC, declaración jurada, entre otros.",
  "artículo 31": "Las propuestas se presentan en dos sobres: 'Documentos Anexos' (identificación, declaraciones, cronograma) y 'Oferta Económica' (formulario, presupuesto detallado).",
  "artículo 33": "En licitaciones indicadas, se pueden presentar variantes o proyectos nuevos por suma alzada, con ventajas técnicas o económicas.",
  "artículo 34": "El presupuesto oficial estimativo es informativo y se usa para el presupuesto compensado. Se entrega el itemizado de partidas en la licitación.",
  "artículo 37": "Las ofertas se abren ante la Comisión Técnica en la fecha indicada, con acta pública y presencia de proponentes.",
  "artículo 39": "Si la resolución de adjudicación no se dicta en 30 días o no se tramita en 60 días, el contratista puede desistirse sin sanción.",
  "artículo 42": "El SERVIU debe contar con bases administrativas y técnicas aprobadas, planos, presupuesto oficial estimativo y financiamiento antes de contratar.",
  "artículo 43": "Los contratos se celebran, modifican y liquidan según el D.S. N° 355 de 1976. No se permiten aumentos por leyes de reajustes o impuestos.",
  "artículo 44": "Los contratos incorporan bases especiales, técnicas, especificaciones, aclaraciones, adiciones, planos y normas vigentes, incluyendo leyes y decretos relacionados.",
  "artículo 45": "Los contratos rigen desde la total tramitación de la resolución de adjudicación. El contratista debe suscribirlo en 15 días.",
  "artículo 46": "Las bases, planos y especificaciones deben ser suscritos por el contratista y depositados en el SERVIU.",
  "artículo 47": "El contratista es responsable de coordinar con empresas de servicios públicos y obtener certificados de recepción.",
  "artículo 48": "Si el contratista proporciona el terreno, debe obtener aprobación de subdivisión y acreditar su inscripción a nombre del SERVIU.",
  "artículo 50": "El contratista entrega una boleta de garantía (3-5% del contrato) antes de suscribir, vigente 30 días más que el plazo contractual.",
  "artículo 51": "El contratista responde por daños a terceros, con una boleta de garantía para indemnizaciones.",
  "artículo 53": "Las boletas de garantía no pueden retenerse, embargarse ni cederse a terceros.",
  "artículo 54": "El traspaso del contrato requiere autorización del Director del SERVIU y nuevas garantías.",
  "artículo 55": "El contratista puede subcontratar según bases especiales, pero responde por todas las obligaciones. Subcontratistas deben estar en el RENAC si superan el 10% del contrato o 8.000 U.F.",
  "artículo 58": "La I.T.O. vela por el cumplimiento de especificaciones técnicas, planos y otras obras del contrato.",
  "artículo 59": "El contratista debe acatar órdenes de la I.T.O. anotadas en el Libro de Inspección. Puede reclamar al Director del SERVIU en 3 días hábiles.",
  "artículo 60": "La I.T.O. ordena suspensiones o despidos de trabajadores/subcontratistas por insubordinación o incapacidad, a través del contratista.",
  "artículo 61": "El contratista reconstruye a su cargo obras o materiales rechazados por la I.T.O.",
  "artículo 64": "La I.T.O. tiene acceso a toda la documentación oficial de la obra y puede requerir copias.",
  "artículo 65": "La I.T.O. controla el avance de las obras según el programa de trabajo y formula estados de pago.",
  "artículo 66": "La I.T.O. informa sobre obras extraordinarias, acordando precios con el contratista, con autorización previa.",
  "artículo 67": "La I.T.O. puede requerir verificación técnica especializada, con honorarios a cargo del SERVIU.",
  "artículo 68": "El contratista debe mantener un Libro de Inspección para órdenes, consultas y apelaciones, entregándolo al SERVIU al finalizar.",
  "artículo 70": "La I.T.O. vela por el cumplimiento de normas laborales y de seguridad del contratista.",
  "artículo 71": "Los profesionales autores de proyectos registran observaciones en el Libro de Obras, autorizadas por la I.T.O. si generan mayores gastos.",
  "artículo 74": "El contratista ejecuta obras según bases, especificaciones y planos, interpretados para la mejor ejecución técnica.",
  "artículo 77": "El contratista presenta la estructura organizacional en 5 días desde la adjudicación, con multa de 2 U.F. diarias por incumplimiento.",
  "artículo 78": "El SERVIU entrega copias de planos y antecedentes sin cargo si los proporcionó. El contratista aprueba proyectos en 15 días si los proporciona.",
  "artículo 80": "El contratista no puede modificar planos o especificaciones sin autorización escrita del SERVIU, con multas o terminación anticipada por incumplimiento.",
  "artículo 83": "Si hay retrasos, el SERVIU ordena normalizar faenas en 15 días.",
  "artículo 84": "Los materiales deben cumplir normas técnicas. Ensayos hasta el 0.5% del contrato son a cargo del contratista; el resto, del SERVIU, salvo defectos.",
  "artículo 85": "Interrupciones por materiales rechazados no dan derecho a prórroga, salvo defectos aceptados inicialmente por la I.T.O.",
  "artículo 86": "Multa diaria de 1/1000 del contrato por retrasos en la entrega o incumplimiento de plazos parciales. Multa de 5 U.F. por otras infracciones si no se especifica.",
  "artículo 87": "Las multas se aplican administrativamente, sin juicio.",
  "artículo 90": "Por ampliaciones de plazo, se indemnizan mayores gastos generales (0.5 por mil del contrato por día).",
  "artículo 91": "El SERVIU puede paralizar obras por falta de fondos o necesidades, con indemnización si excede 2 meses.",
  "artículo 94": "El contratista debe proporcionar datos solicitados por el SERVIU, con multa de 2 U.F. diarias por incumplimiento.",
  "artículo 95": "El contratista proporciona campamentos adecuados para trabajadores en obras alejadas, según normas de salubridad y seguridad.",
  "artículo 96": "El SERVIU puede pagar remuneraciones o imposiciones adeudadas por el contratista, imputándolas a pagos pendientes.",
  "artículo 97": "El contratista responde por daños a terceros, como ocupación de terrenos o corta de árboles, salvo expropiaciones a cargo del SERVIU.",
  "artículo 99": "El contratista cubre maquinaria, herramientas, instalaciones, seguridad y gastos adicionales, salvo lo estipulado en bases especiales.",
  "artículo 100": "Incendios o accidentes fortuitos son responsabilidad del contratista, salvo materiales del SERVIU.",
  "artículo 104": "El Director del SERVIU puede contratar obras extraordinarias hasta el 15% del contrato, con autorización según el monto.",
  "artículo 105": "El contratista gestiona servidumbres, concesiones y permisos necesarios para la obra.",
  "artículo 106": "El contratista coloca letreros de identificación según normas del SERVIU, a su cargo.",
  "artículo 107": "El contratista instala señalización provisional durante la obra y la retira al finalizar.",
  "artículo 110": "El contratista despeja materiales excedentes, escombros y basuras al finalizar la obra.",
  "artículo 111": "El contratista es responsable de la seguridad y cuidado de las obras durante su ejecución.",
  "artículo 112": "El SERVIU puede intervenir en accidentes o fallas no resueltas por el contratista, deduciendo costos de estados de pago.",
  "artículo 113": "Imprecisiones en planos o antecedentes se resuelven para beneficiar el proyecto, según reglas técnicas.",
  "artículo 114": "Los estados de pago se formulan cada 28 días, basados en el presupuesto compensado, con firma del Director de la Obra y el contratista.",
  "artículo 115": "Los estados de pago son anticipos, no aceptación de calidad. Se formulan por obras ejecutadas, con firmas requeridas.",
  "artículo 116": "Los estados de pago y presupuestos se expresan en U.F., convertidos a pesos a la fecha de emisión del documento de pago.",
  "artículo 117": "Los reajustes se pagan en estados de pago separados, numerados con 'R'.",
  "artículo 118": "Los pagos se reajustan según la U.F. hasta la fecha de vencimiento del contrato o de la resolución que autoriza el pago.",
  "artículo 122": "El SERVIU puede otorgar anticipos por materiales (hasta 60% del contrato) o en dinero, descontados de estados de pago.",
  "artículo 123": "El contratista solicita la recepción de obras. La I.T.O. verifica en 2 días hábiles y comunica conformidad o reparos.",
  "artículo 124": "Si la obra no está terminada o tiene defectos, la recepción se suspende hasta subsanar reparos, con plazo máximo del 10% del contrato.",
  "artículo 126": "Tras la recepción, el contratista entrega una boleta de garantía (3% del contrato) por buen comportamiento, vigente al menos 2 años.",
  "artículo 127": "El contratista repara defectos durante el plazo de garantía, salvo uso inadecuado por el SERVIU.",
  "artículo 129": "La recepción requiere certificados como el de copropiedad inmobiliaria o calificación ambiental, según bases especiales.",
  "artículo 131": "Si no se subsanan observaciones en el plazo de garantía, se exige una nueva garantía de 90 días para reparaciones.",
  "artículo 133": "La terminación anticipada del contrato se hace por resolución fundada del Director del SERVIU, sin juicio.",
  "artículo 134": "Causales de terminación anticipada incluyen quiebra, incumplimiento de plazos, defectos graves, o negativa a renovar garantías.",
  "artículo 135": "En terminación anticipada, se hace efectiva la boleta de garantía para cubrir costos de rehacer o reparar obras.",
  "artículo 138": "Si el contratista propone modificaciones que generan ahorros superiores al 10%, recibe un premio del 50% de la economía.",
  "artículo 139": "Las bases especiales pueden establecer premios por calidad, seguridad o cumplimiento de métodos constructivos.",
  "artículo 140": "Las compras de materiales o arrendamientos (operaciones) se rigen por este título, con autorización del Director del SERVIU.",
  "artículo 141": "Las operaciones se efectúan según presupuestos estimativos, con procedimientos según el artículo 4.",
  "artículo 142": "Las operaciones se hacen por trato directo (hasta 8.500 U.F.), propuesta privada, o propuesta pública (más de 8.500 U.F.).",
  "artículo 143": "El SERVIU puede pactar modalidades de entrega y pago con proveedores, incluyendo reajustes si procede.",
  "artículo 144": "Licitaciones y contratos de pavimentación se rigen por manuales y normas técnicas de vialidad y pavimentación del MINVU y MOP.",
  "pavimentos": "Deben cumplir con el Código de Normas y Especificaciones Técnicas de Obras de Pavimentación (Publicación N° 291, MINVU, 1984), Manual de Vialidad Urbana, y D.S. N° 411 de 1948 del MOP, según el artículo 144.",
  "inspección técnica": "La I.T.O., designada por el Director del SERVIU, supervisa el cumplimiento del contrato, realiza inspecciones selectivas, verifica autocontrol y cursa estados de pago, según artículos 55-71 y el Manual de Inspección Técnica de Obras (D.S. N° 137, 1998)."
};